
services:
  backend:
    build: ./backend
    ports:
      - "8002:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend-next
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8002
    depends_on:
      - backend
